spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.175.18:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: blog
    password: blog
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.linyk3: debug
  file: log/blog-dev.log

file:
  filePath: "C:\\Users\\linyk3\\Desktop\\imageFile\\"
  download:
    prefix: "http://localhost:9001/image/download/"

